---
kind: pipeline
name: anti-preempter

# steps:
# - name: build  
#   image: plugins/docker
#   settings:
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#     repo: index.company.com/foo/bar
#     registry: eu.gcr.io
#     auto_tag: true
# when:
#   event:
#   - push


steps:
- name: publish  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo: moss-work/anti-preempter
    tags: latest
    json_key:
      from_secret: MW_PUSH_CREDS
  when:
    event: push
    branch: master
- name: deploy
  image: eu.gcr.io/moss-work/drone-gke-deployer:latest
  commands:
  - ./go test
  when:
    event: push
    branch: master
---
kind: signature
hmac: 9d268d30d09f6f467b094c8d0449cff1a3d2b30c506400c4b1cbe0efa454bb4b

...
