---
kind: pipeline
name: anti-preempter

steps:
- name: publish  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo: moss-work/anti-preempter
    tags: latest
    json_key:
      from_secret: MW_PUSH_CREDS
  when:
    event: push
    branch: master
- name: deploy
  image: mosstech/drone-gke-deployer:latest
  environment:
    NAMESPACE: mw-platform
    GCP_PROJECT_ID: moss-work
    K8S_DEPLOYER_CREDS:
      from_secret: MW_K8S_DEPLOYER
    K8S_CLUSTER_NAME:
      from_secret: MW_K8S_CLUSTER_NAME
    GOOGLE_CREDS:
      from_secret: MW_PREEMPT_MANAGER
  commands:
  - ./go deploy
  when:
    event: push
    branch: master
---
kind: signature
hmac: e860c3b4c8a092e2a8ae6f48bc95d8e4a23cd6fcd15b6152a249b6bdbad9f4e8

...
