---
kind: pipeline
name: anti-preempter

steps:
- name: publish  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo: moss-work/anti-preempter
    tags: latest
    json_key:
      from_secret: MW_PUSH_CREDS
  when:
    event: push
    branch: master
- name: deploy
  image: mosstech/drone-gke-deployer:latest
  environment:
    GCP_PROJECT_NAME:
      from_secret: GCP_PROJECT_NAME
    K8S_CLUSTER_NAME:
      from_secret: K8S_CLUSTER_NAME
    K8S_CLUSTER_REGION:
      from_secret: K8S_CLUSTER_REGION
  commands:
  - ./go deploy
  when:
    event: push
    branch: master
---
kind: signature
hmac: 48709a34581965336c3c635baffdc113364080b3d89f79dce4b8f0e13df26150

...
