---
kind: pipeline
name: anti-preempter

steps:
- name: publish  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo: grand-signifier-297613/anti-preempter
    tags: latest
    json_key:
      from_secret: MW_PUSH_CREDS
    config:
      from_secret: DOCKER_AUTH_CONFIG
  when:
    event: push
    branch: master
- name: deploy
  image: mosstech/drone-gke-deployer:latest
  environment:
    NAMESPACE: anti-preempter
    GCP_PROJECT_ID:
      from_secret: MW_GCP_PROJECT_ID
    K8S_DEPLOYER_CREDS:
      from_secret: MW_K8S_DEPLOYER
    K8S_CLUSTER_NAME:
      from_secret: MW_K8S_CLUSTER_NAME
    GOOGLE_CREDS:
      from_secret: MW_PREEMPT_MANAGER
  commands:
  - ./go deploy
  when:
    event: push
    branch: master
---
kind: signature
hmac: 152262e6b7ef2b36bf4aacd5ec308c62d78cd5e5ee8fbfb46b811801ac33894d

...
