---
kind: pipeline
name: anti-preempter

steps:
- name: publish  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo: moss-work/anti-preempter
    tags: latest
    json_key:
      from_secret: MW_PUSH_CREDS
  when:
    event: push
    branch: master
- name: deploy
  image: alexdmoss/drone-gke-deployer:latest
  commands:
  - ./go test
  when:
    event: push
    branch: master
---
kind: signature
hmac: 6fa452d235ad00149cd91cb40274fb659471ce544d86d5dd827296aed28e7775

...
