---
kind: pipeline
name: anti-preempter

steps:
- name: publish  
  image: plugins/gcr
  settings:
    registry: eu.gcr.io
    repo: moss-work/anti-preempter
    tags: latest
    json_key:
      from_secret: MW_PUSH_CREDS
  when:
    event: push
    branch: master
- name: deploy
  image: mosstech/drone-gke-deployer:latest
  environment:
    K8S_DEPLOYER_CREDS:
      from_secret: MW_K8S_DEPLOYER
    K8S_CLUSTER_NAME:
      from_secret: MW_K8S_CLUSTER_NAME
  commands:
  - ./go deploy
  when:
    event: push
    branch: master
---
kind: signature
hmac: b9e44e8d10ba0a74d5bf0cd8e3e11bff60da4647ef001dac2204f391e1d4f2fd

...
