apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: anti-preempter-job
  namespace: ${NAMESPACE}
spec:
  schedule: "00 * * * *"
  # schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: anti-preempter
            image: eu.gcr.io/moss-work/anti-preempter:latest
            env:
            - name: INSTANCE_INTERVAL
              value: "600"
            - name: GCP_PROJECT_ID
              value: ${GCP_PROJECT_ID}
            - name: GOOGLE_CREDS
              valueFrom:
                secretKeyRef:
                  name: anti-preempter-creds
                  key: google_creds
            ### dry-run switch
            # args:
            # - -t
          restartPolicy: OnFailure
---
